const userdatapendingtype = {
  id: 2751,
  username: "080-22133159@hph.com",
  email: "080-22133159@hph.com",
  dob: null,
  gotra: null,
  sex: null,
  emeelanrole: "MEELAN",
  userstatus: "PENDING",
  firstname: "BHURARAMJI SENCHA",
  lastname: null,
  jati: null,
  cast: null,
  isdivyang: false,
  divyangdescription: null,
  relationship: null,
  ISActiveProfile: null,
  language: null,
  bio: null,
  companyName: null,
  privacy: null,
  education_level: null,
  user_title: null,
  father_gotra: null,
  mobile: null,
  agora_client_user_id: null,
  userrole: null,
  dial_code: null,
  record_create_by_user: null,
  father: null,
  mother: null,
  husband: null,
  marital: null,
  occupation: null,
  createdAt: "2024-05-31T15:34:19.836Z",
  updatedAt: "2024-06-19T09:57:11.261Z",
};

export default userdatapendingtype;
